name: Dispatch workflow

on:
  repository_dispatch:
    types: proba

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Calculate branch
        run: |
                echo "${{ github.event.client_payload.uno }}"
                echo "${{ github.event.client_payload.dos }}"
                echo "${{ github.event.client_payload.tres }}"

